const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  console.log('--- Iniciando modernização do Banco de Dados ---');

  const sqlCommands = [
    // 1. Tabela agendamentos (Modernizada)
    `CREATE TABLE IF NOT EXISTS public.agendamentos (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      id_cliente UUID, 
      id_barbeiro BIGINT NOT NULL,
      id_servico BIGINT NOT NULL,
      data_hora_agendamento TIMESTAMPTZ NOT NULL,
      status TEXT DEFAULT 'agendado' CHECK (status IN ('agendado', 'concluido', 'cancelado')),
      valor NUMERIC(10, 2) NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      deleted_at TIMESTAMPTZ,
      CONSTRAINT fk_barbeiro FOREIGN KEY (id_barbeiro) REFERENCES public."Barber"(id) ON DELETE CASCADE,
      CONSTRAINT fk_servico FOREIGN KEY (id_servico) REFERENCES public."Service"(id) ON DELETE CASCADE
    );`,

    // 2. Índice Único (Impedir choque de horário)
    `DROP INDEX IF EXISTS idx_unique_barbeiro_horario;`,
    `CREATE UNIQUE INDEX idx_unique_barbeiro_horario 
     ON public.agendamentos (id_barbeiro, data_hora_agendamento) 
     WHERE deleted_at IS NULL;`,

    // 3. Trava de Segurança: Agendamento Retroativo
    `ALTER TABLE public.agendamentos DROP CONSTRAINT IF EXISTS check_data_futura;`,
    `ALTER TABLE public.agendamentos ADD CONSTRAINT check_data_futura 
     CHECK (data_hora_agendamento > NOW());`,

    // 4. View para Agendamentos Ativos (Soft Delete)
    `CREATE OR REPLACE VIEW public.v_agendamentos_ativos AS
     SELECT id, id_cliente, id_barbeiro, id_servico, data_hora_agendamento, valor, status
     FROM public.agendamentos
     WHERE deleted_at IS NULL;`,

    // 5. Função RPC: Check de Disponibilidade com Sobreposição
    `CREATE OR REPLACE FUNCTION check_disponibilidade(
      p_barbeiro_id BIGINT,
      p_inicio TIMESTAMPTZ,
      p_duracao_nova_minutos INT
    ) 
    RETURNS BOOLEAN AS $$
    DECLARE
      v_fim_novo TIMESTAMPTZ;
      v_existe_conflito BOOLEAN;
    BEGIN
      v_fim_novo := p_inicio + (p_duracao_nova_minutos * interval '1 minute');

      SELECT EXISTS (
        SELECT 1 
        FROM public.agendamentos a
        JOIN public."Service" s ON a.id_servico = s.id
        WHERE a.id_barbeiro = p_barbeiro_id
          AND a.deleted_at IS NULL
          AND (
            a.data_hora_agendamento < v_fim_novo
            AND 
            (a.data_hora_agendamento + (CAST(substring(s.duration from '^[0-9]+') AS INT) * interval '1 minute')) > p_inicio
          )
      ) INTO v_existe_conflito;

      RETURN NOT v_existe_conflito;
    END;
    $$ LANGUAGE plpgsql;`
  ];

  for (const sql of sqlCommands) {
    try {
      await prisma.$executeRawUnsafe(sql);
      console.log('✅ Comando executado com sucesso.');
    } catch (err) {
      console.error('❌ Erro ao executar comando:', err.message);
    }
  }

  console.log('--- Modernização concluída! ---');
}

main()
  .catch(e => console.error(e))
  .finally(async () => {
    await prisma.$disconnect();
  });
