const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  console.log('--- Iniciando Implementação de Horários de Funcionamento ---');

  const sqlCommands = [
    // 1. Criar Tabelas
    `CREATE TABLE IF NOT EXISTS public.horarios_funcionamento (
      dia_semana INT PRIMARY KEY,
      is_aberto BOOLEAN DEFAULT true,
      hora_abertura TIME NOT NULL,
      hora_fechamento TIME NOT NULL,
      almoco_inicio TIME,
      almoco_fim TIME
    );`,

    `CREATE TABLE IF NOT EXISTS public.feriados (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      data DATE UNIQUE NOT NULL,
      descricao TEXT
    );`,

    // 2. Popular Horários Padrão (Segunda a Sábado 09:00 - 19:00, Almoço 12:00 - 13:00)
    `INSERT INTO public.horarios_funcionamento (dia_semana, is_aberto, hora_abertura, hora_fechamento, almoco_inicio, almoco_fim)
     VALUES 
      (1, true, '09:00', '19:00', '12:00', '13:00'), -- Segunda
      (2, true, '09:00', '19:00', '12:00', '13:00'), -- Terça
      (3, true, '09:00', '19:00', '12:00', '13:00'), -- Quarta
      (4, true, '09:00', '19:00', '12:00', '13:00'), -- Quinta
      (5, true, '09:00', '19:00', '12:00', '13:00'), -- Sexta
      (6, true, '09:00', '18:00', '12:00', '13:00'), -- Sábado (fechando 18h por exemplo)
      (0, false, '00:00', '00:00', NULL, NULL)      -- Domingo (Fechado)
     ON CONFLICT (dia_semana) DO UPDATE SET 
      is_aberto = EXCLUDED.is_aberto,
      hora_abertura = EXCLUDED.hora_abertura,
      hora_fechamento = EXCLUDED.hora_fechamento,
      almoco_inicio = EXCLUDED.almoco_inicio,
      almoco_fim = EXCLUDED.almoco_fim;`,

    // 3. Evolução da Função check_disponibilidade (Agora com regras de expediente)
    `CREATE OR REPLACE FUNCTION check_disponibilidade(
      p_barbeiro_id BIGINT,
      p_inicio TIMESTAMPTZ,
      p_duracao_nova_minutos INT
    ) 
    RETURNS JSONB AS $$
    DECLARE
      v_fim_novo TIMESTAMPTZ;
      v_dia_semana INT;
      v_data_pura DATE;
      v_hora_inicio TIME;
      v_hora_fim TIME;
      v_regra RECORD;
      v_existe_conflito BOOLEAN;
      v_is_feriado BOOLEAN;
    BEGIN
      v_fim_novo := p_inicio + (p_duracao_nova_minutos * interval '1 minute');
      v_dia_semana := EXTRACT(DOW FROM p_inicio); -- 0 a 6
      v_data_pura := p_inicio::DATE;
      v_hora_inicio := p_inicio::TIME;
      v_hora_fim := v_fim_novo::TIME;

      -- 1. Verifica se é feriado
      SELECT EXISTS (SELECT 1 FROM public.feriados WHERE data = v_data_pura) INTO v_is_feriado;
      IF v_is_feriado THEN
        RETURN jsonb_build_object('disponivel', false, 'motivo', 'Feriado: a barbearia não abrirá nesta data.');
      END IF;

      -- 2. Busca regra do dia da semana
      SELECT * INTO v_regra FROM public.horarios_funcionamento WHERE dia_semana = v_dia_semana;
      
      -- 3. Valida se está aberto no dia
      IF NOT v_regra.is_aberto THEN
        RETURN jsonb_build_object('disponivel', false, 'motivo', 'Barbearia fechada neste dia da semana.');
      END IF;

      -- 4. Valida se o horário está dentro do expediente (Abertura e Fechamento)
      IF v_hora_inicio < v_regra.hora_abertura OR v_hora_fim > v_regra.hora_fechamento THEN
        RETURN jsonb_build_object('disponivel', false, 'motivo', 'Horário fora do expediente (Abre ' || v_regra.hora_abertura || ', Fecha ' || v_regra.hora_fechamento || ').');
      END IF;

      -- 5. Valida choque com horário de almoço
      -- Se o agendamento COMEÇA ou TERMINA durante o almoço
      IF (v_hora_inicio >= v_regra.almoco_inicio AND v_hora_inicio < v_regra.almoco_fim) OR
         (v_hora_fim > v_regra.almoco_inicio AND v_hora_fim <= v_regra.almoco_fim) OR
         (v_hora_inicio < v_regra.almoco_inicio AND v_hora_fim > v_regra.almoco_fim) THEN
        RETURN jsonb_build_object('disponivel', false, 'motivo', 'O horário selecionado choca com o intervalo de almoço.');
      END IF;

      -- 6. Verifica sobreposição com outros agendamentos (Overlap)
      SELECT EXISTS (
        SELECT 1 
        FROM public.agendamentos a
        JOIN public."Service" s ON a.id_servico = s.id
        WHERE a.id_barbeiro = p_barbeiro_id
          AND a.deleted_at IS NULL
          AND (a.data_hora_agendamento < v_fim_novo AND (a.data_hora_agendamento + (CAST(substring(s.duration from '^[0-9]+') AS INT) * interval '1 minute')) > p_inicio)
      ) INTO v_existe_conflito;

      IF v_existe_conflito THEN
        RETURN jsonb_build_object('disponivel', false, 'motivo', 'Já existe um agendamento para este profissional neste horário.');
      END IF;

      -- TUDO OK!
      RETURN jsonb_build_object('disponivel', true, 'motivo', 'Horário disponível.');
    END;
    $$ LANGUAGE plpgsql;`
  ];

  for (const sql of sqlCommands) {
    try {
      await prisma.$executeRawUnsafe(sql);
      console.log('✅ Executado com sucesso.');
    } catch (err) {
      console.error('❌ Erro:', err.message);
    }
  }

  console.log('--- Configuração de Horários Finalizada! ---');
}

main()
  .catch(e => console.error(e))
  .finally(async () => await prisma.$disconnect());
